#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPJWebsite
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PPJ")]
	public partial class PPJDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertJalanTempah(JalanTempah instance);
    partial void UpdateJalanTempah(JalanTempah instance);
    partial void DeleteJalanTempah(JalanTempah instance);
    partial void InsertJalanInfo(JalanInfo instance);
    partial void UpdateJalanInfo(JalanInfo instance);
    partial void DeleteJalanInfo(JalanInfo instance);
    #endregion
		
		public PPJDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PPJConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PPJDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PPJDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PPJDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PPJDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<JalanTempah> JalanTempahs
		{
			get
			{
				return this.GetTable<JalanTempah>();
			}
		}
		
		public System.Data.Linq.Table<JalanInfo> JalanInfos
		{
			get
			{
				return this.GetTable<JalanInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JalanTempah")]
	public partial class JalanTempah : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NoRujukanTempah;
		
		private string _NoRujukanPermohonan;
		
		private System.Nullable<int> _NoRujukanJalan;
		
		private System.Nullable<int> _JumlahTiangTempah;
		
		private System.Nullable<System.DateTime> _TarikhMula;
		
		private System.Nullable<System.DateTime> _TarikhTamat;
		
		private System.Nullable<double> _HargaSeunit;
		
		private System.Nullable<double> _Jumlah;
		
		private System.Nullable<System.DateTime> _TarikhData;
		
		private EntityRef<JalanInfo> _JalanInfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoRujukanTempahChanging(int value);
    partial void OnNoRujukanTempahChanged();
    partial void OnNoRujukanPermohonanChanging(string value);
    partial void OnNoRujukanPermohonanChanged();
    partial void OnNoRujukanJalanChanging(System.Nullable<int> value);
    partial void OnNoRujukanJalanChanged();
    partial void OnJumlahTiangTempahChanging(System.Nullable<int> value);
    partial void OnJumlahTiangTempahChanged();
    partial void OnTarikhMulaChanging(System.Nullable<System.DateTime> value);
    partial void OnTarikhMulaChanged();
    partial void OnTarikhTamatChanging(System.Nullable<System.DateTime> value);
    partial void OnTarikhTamatChanged();
    partial void OnHargaSeunitChanging(System.Nullable<double> value);
    partial void OnHargaSeunitChanged();
    partial void OnJumlahChanging(System.Nullable<double> value);
    partial void OnJumlahChanged();
    partial void OnTarikhDataChanging(System.Nullable<System.DateTime> value);
    partial void OnTarikhDataChanged();
    #endregion
		
		public JalanTempah()
		{
			this._JalanInfo = default(EntityRef<JalanInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoRujukanTempah", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NoRujukanTempah
		{
			get
			{
				return this._NoRujukanTempah;
			}
			set
			{
				if ((this._NoRujukanTempah != value))
				{
					this.OnNoRujukanTempahChanging(value);
					this.SendPropertyChanging();
					this._NoRujukanTempah = value;
					this.SendPropertyChanged("NoRujukanTempah");
					this.OnNoRujukanTempahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoRujukanPermohonan", DbType="VarChar(250)")]
		public string NoRujukanPermohonan
		{
			get
			{
				return this._NoRujukanPermohonan;
			}
			set
			{
				if ((this._NoRujukanPermohonan != value))
				{
					this.OnNoRujukanPermohonanChanging(value);
					this.SendPropertyChanging();
					this._NoRujukanPermohonan = value;
					this.SendPropertyChanged("NoRujukanPermohonan");
					this.OnNoRujukanPermohonanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoRujukanJalan", DbType="Int")]
		public System.Nullable<int> NoRujukanJalan
		{
			get
			{
				return this._NoRujukanJalan;
			}
			set
			{
				if ((this._NoRujukanJalan != value))
				{
					if (this._JalanInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoRujukanJalanChanging(value);
					this.SendPropertyChanging();
					this._NoRujukanJalan = value;
					this.SendPropertyChanged("NoRujukanJalan");
					this.OnNoRujukanJalanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumlahTiangTempah", DbType="Int")]
		public System.Nullable<int> JumlahTiangTempah
		{
			get
			{
				return this._JumlahTiangTempah;
			}
			set
			{
				if ((this._JumlahTiangTempah != value))
				{
					this.OnJumlahTiangTempahChanging(value);
					this.SendPropertyChanging();
					this._JumlahTiangTempah = value;
					this.SendPropertyChanged("JumlahTiangTempah");
					this.OnJumlahTiangTempahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhMula", DbType="Date")]
		public System.Nullable<System.DateTime> TarikhMula
		{
			get
			{
				return this._TarikhMula;
			}
			set
			{
				if ((this._TarikhMula != value))
				{
					this.OnTarikhMulaChanging(value);
					this.SendPropertyChanging();
					this._TarikhMula = value;
					this.SendPropertyChanged("TarikhMula");
					this.OnTarikhMulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhTamat", DbType="Date")]
		public System.Nullable<System.DateTime> TarikhTamat
		{
			get
			{
				return this._TarikhTamat;
			}
			set
			{
				if ((this._TarikhTamat != value))
				{
					this.OnTarikhTamatChanging(value);
					this.SendPropertyChanging();
					this._TarikhTamat = value;
					this.SendPropertyChanged("TarikhTamat");
					this.OnTarikhTamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaSeunit", DbType="Float")]
		public System.Nullable<double> HargaSeunit
		{
			get
			{
				return this._HargaSeunit;
			}
			set
			{
				if ((this._HargaSeunit != value))
				{
					this.OnHargaSeunitChanging(value);
					this.SendPropertyChanging();
					this._HargaSeunit = value;
					this.SendPropertyChanged("HargaSeunit");
					this.OnHargaSeunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah", DbType="Float")]
		public System.Nullable<double> Jumlah
		{
			get
			{
				return this._Jumlah;
			}
			set
			{
				if ((this._Jumlah != value))
				{
					this.OnJumlahChanging(value);
					this.SendPropertyChanging();
					this._Jumlah = value;
					this.SendPropertyChanged("Jumlah");
					this.OnJumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhData", DbType="DateTime")]
		public System.Nullable<System.DateTime> TarikhData
		{
			get
			{
				return this._TarikhData;
			}
			set
			{
				if ((this._TarikhData != value))
				{
					this.OnTarikhDataChanging(value);
					this.SendPropertyChanging();
					this._TarikhData = value;
					this.SendPropertyChanged("TarikhData");
					this.OnTarikhDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JalanInfo_JalanTempah", Storage="_JalanInfo", ThisKey="NoRujukanJalan", OtherKey="NoRujukanJalan", IsForeignKey=true)]
		public JalanInfo JalanInfo
		{
			get
			{
				return this._JalanInfo.Entity;
			}
			set
			{
				JalanInfo previousValue = this._JalanInfo.Entity;
				if (((previousValue != value) 
							|| (this._JalanInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._JalanInfo.Entity = null;
						previousValue.JalanTempahs.Remove(this);
					}
					this._JalanInfo.Entity = value;
					if ((value != null))
					{
						value.JalanTempahs.Add(this);
						this._NoRujukanJalan = value.NoRujukanJalan;
					}
					else
					{
						this._NoRujukanJalan = default(Nullable<int>);
					}
					this.SendPropertyChanged("JalanInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JalanInfo")]
	public partial class JalanInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NoRujukanJalan;
		
		private string _NamaJalan;
		
		private System.Nullable<int> _JumlahTiang;
		
		private System.Nullable<int> _Rosak;
		
		private System.Nullable<int> _Tersedia;
		
		private System.Nullable<int> _JumlahArm;
		
		private string _SaizGegantung;
		
		private System.Nullable<double> _HargaKosSeunit;
		
		private System.Nullable<double> _HargaSeunit;
		
		private System.Nullable<bool> _Aktif;
		
		private System.Nullable<System.DateTime> _TarikhData;
		
		private EntitySet<JalanTempah> _JalanTempahs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoRujukanJalanChanging(int value);
    partial void OnNoRujukanJalanChanged();
    partial void OnNamaJalanChanging(string value);
    partial void OnNamaJalanChanged();
    partial void OnJumlahTiangChanging(System.Nullable<int> value);
    partial void OnJumlahTiangChanged();
    partial void OnRosakChanging(System.Nullable<int> value);
    partial void OnRosakChanged();
    partial void OnTersediaChanging(System.Nullable<int> value);
    partial void OnTersediaChanged();
    partial void OnJumlahArmChanging(System.Nullable<int> value);
    partial void OnJumlahArmChanged();
    partial void OnSaizGegantungChanging(string value);
    partial void OnSaizGegantungChanged();
    partial void OnHargaKosSeunitChanging(System.Nullable<double> value);
    partial void OnHargaKosSeunitChanged();
    partial void OnHargaSeunitChanging(System.Nullable<double> value);
    partial void OnHargaSeunitChanged();
    partial void OnAktifChanging(System.Nullable<bool> value);
    partial void OnAktifChanged();
    partial void OnTarikhDataChanging(System.Nullable<System.DateTime> value);
    partial void OnTarikhDataChanged();
    #endregion
		
		public JalanInfo()
		{
			this._JalanTempahs = new EntitySet<JalanTempah>(new Action<JalanTempah>(this.attach_JalanTempahs), new Action<JalanTempah>(this.detach_JalanTempahs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoRujukanJalan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NoRujukanJalan
		{
			get
			{
				return this._NoRujukanJalan;
			}
			set
			{
				if ((this._NoRujukanJalan != value))
				{
					this.OnNoRujukanJalanChanging(value);
					this.SendPropertyChanging();
					this._NoRujukanJalan = value;
					this.SendPropertyChanged("NoRujukanJalan");
					this.OnNoRujukanJalanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaJalan", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string NamaJalan
		{
			get
			{
				return this._NamaJalan;
			}
			set
			{
				if ((this._NamaJalan != value))
				{
					this.OnNamaJalanChanging(value);
					this.SendPropertyChanging();
					this._NamaJalan = value;
					this.SendPropertyChanged("NamaJalan");
					this.OnNamaJalanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumlahTiang", DbType="Int")]
		public System.Nullable<int> JumlahTiang
		{
			get
			{
				return this._JumlahTiang;
			}
			set
			{
				if ((this._JumlahTiang != value))
				{
					this.OnJumlahTiangChanging(value);
					this.SendPropertyChanging();
					this._JumlahTiang = value;
					this.SendPropertyChanged("JumlahTiang");
					this.OnJumlahTiangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rosak", DbType="Int")]
		public System.Nullable<int> Rosak
		{
			get
			{
				return this._Rosak;
			}
			set
			{
				if ((this._Rosak != value))
				{
					this.OnRosakChanging(value);
					this.SendPropertyChanging();
					this._Rosak = value;
					this.SendPropertyChanged("Rosak");
					this.OnRosakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tersedia", DbType="Int")]
		public System.Nullable<int> Tersedia
		{
			get
			{
				return this._Tersedia;
			}
			set
			{
				if ((this._Tersedia != value))
				{
					this.OnTersediaChanging(value);
					this.SendPropertyChanging();
					this._Tersedia = value;
					this.SendPropertyChanged("Tersedia");
					this.OnTersediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumlahArm", DbType="Int")]
		public System.Nullable<int> JumlahArm
		{
			get
			{
				return this._JumlahArm;
			}
			set
			{
				if ((this._JumlahArm != value))
				{
					this.OnJumlahArmChanging(value);
					this.SendPropertyChanging();
					this._JumlahArm = value;
					this.SendPropertyChanged("JumlahArm");
					this.OnJumlahArmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaizGegantung", DbType="VarChar(250)")]
		public string SaizGegantung
		{
			get
			{
				return this._SaizGegantung;
			}
			set
			{
				if ((this._SaizGegantung != value))
				{
					this.OnSaizGegantungChanging(value);
					this.SendPropertyChanging();
					this._SaizGegantung = value;
					this.SendPropertyChanged("SaizGegantung");
					this.OnSaizGegantungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaKosSeunit", DbType="Float")]
		public System.Nullable<double> HargaKosSeunit
		{
			get
			{
				return this._HargaKosSeunit;
			}
			set
			{
				if ((this._HargaKosSeunit != value))
				{
					this.OnHargaKosSeunitChanging(value);
					this.SendPropertyChanging();
					this._HargaKosSeunit = value;
					this.SendPropertyChanged("HargaKosSeunit");
					this.OnHargaKosSeunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaSeunit", DbType="Float")]
		public System.Nullable<double> HargaSeunit
		{
			get
			{
				return this._HargaSeunit;
			}
			set
			{
				if ((this._HargaSeunit != value))
				{
					this.OnHargaSeunitChanging(value);
					this.SendPropertyChanging();
					this._HargaSeunit = value;
					this.SendPropertyChanged("HargaSeunit");
					this.OnHargaSeunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktif", DbType="Bit")]
		public System.Nullable<bool> Aktif
		{
			get
			{
				return this._Aktif;
			}
			set
			{
				if ((this._Aktif != value))
				{
					this.OnAktifChanging(value);
					this.SendPropertyChanging();
					this._Aktif = value;
					this.SendPropertyChanged("Aktif");
					this.OnAktifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhData", DbType="DateTime")]
		public System.Nullable<System.DateTime> TarikhData
		{
			get
			{
				return this._TarikhData;
			}
			set
			{
				if ((this._TarikhData != value))
				{
					this.OnTarikhDataChanging(value);
					this.SendPropertyChanging();
					this._TarikhData = value;
					this.SendPropertyChanged("TarikhData");
					this.OnTarikhDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JalanInfo_JalanTempah", Storage="_JalanTempahs", ThisKey="NoRujukanJalan", OtherKey="NoRujukanJalan")]
		public EntitySet<JalanTempah> JalanTempahs
		{
			get
			{
				return this._JalanTempahs;
			}
			set
			{
				this._JalanTempahs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_JalanTempahs(JalanTempah entity)
		{
			this.SendPropertyChanging();
			entity.JalanInfo = this;
		}
		
		private void detach_JalanTempahs(JalanTempah entity)
		{
			this.SendPropertyChanging();
			entity.JalanInfo = null;
		}
	}
}
#pragma warning restore 1591
